{% set name = "materials-learning-algorithms" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mala-project/mala/archive/v{{ version }}.tar.gz
  sha256: 1ef396192b0c5e561bde8e79c4834d295cdd055dc9ef68f3e8b2d68e837035c5
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ase
    - mpmath
    - numpy
    - optuna
    - scipy
    - pandas
    - tensorboard
    - pytorch
    - openpmd-api

test:
  imports:
    - mala
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mala-project/mala
  summary: Materials Learning Algorithms. A framework for machine learning materials properties from first-principles data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
