{% set name = "materials-learning-algorithms" %}
{% set version = "1.4.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mala-project/mala/archive/v{{ version }}.tar.gz
  sha256: ecc5bc41082a26e3e8bc2341da0c8948463455e007db0f43044f3ffdb645d0c3
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ase
    - mpmath
    - numpy >=2
    - optuna
    - scipy
    - pandas
    - tensorboard
    - pytorch
    - openpmd-api
    - scikit-spatial
    - tqdm
    - mendeleev >=1.0.0

test:
  imports:
    - mala
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mala-project/mala
  summary: Materials Learning Algorithms. A framework for machine learning materials properties from first-principles data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
