{% set name = "materials-learning-algorithms" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mala-project/mala/archive/v{{ version }}.tar.gz
  sha256: 2b8f1b719e8d0138b9066339911291140af811ce3d087997f223f00884a4614b
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ase
    - mpmath
    - numpy
    - optuna
    - scipy
    - pandas
    - tensorboard
    - pytorch
    - openpmd-api

test:
  imports:
    - mala
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mala-project/mala
  summary: Materials Learning Algorithms. A framework for machine learning materials properties from first-principles data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
